export type TagsNodesRelevant =
  | 'addr:city'
  | 'addr:country'
  | 'addr:housenumber'
  | 'addr:housenumber_official'
  | 'addr:postcode'
  | 'addr:street'
  | 'addr:suburb'
  | 'amenity'
  | 'building'
  | 'name';

export type TagsWaysRelevant =
  | 'addr:alt_street'
  | 'addr:block'
  | 'addr:city'
  | 'addr:country'
  | 'addr:district'
  | 'addr:garagenumber'
  | 'addr:housename'
  | 'addr:housenumber'
  | 'addr:housenumber:source'
  | 'addr:official_street'
  | 'addr:old_housenumber'
  | 'addr:place'
  | 'addr:postcode'
  | 'addr:province'
  | 'addr:source'
  | 'addr:state'
  | 'addr:street'
  | 'addr:subdistrict'
  | 'addr:suburb'
  | 'addr:town'
  | 'amenity'
  | 'building'
  | 'name';
